# Generated by Django 2.0.7 on 2018-07-17 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('family_name', models.CharField(max_length=150, verbose_name='Family')),
                ('active', models.BooleanField(default=True)),
                ('judge', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.TextField(blank=True, null=True)),
                ('finished', models.PositiveSmallIntegerField(default=0)),
                ('party', models.ManyToManyField(related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('dispute_start_allowed', models.DateField()),
                ('dispute_started', models.DateField(blank=True, default=None, null=True)),
                ('result_file', models.CharField(blank=True, max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='dispute_resolution.ContractCase')),
                ('dispute_starter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_disputes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_stages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('fin', 'Finished'), ('disp_open', 'Disput Opened'), ('open', 'Opened'), ('disp_close', 'Dispute Closed')], default='open', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='dispute_resolution.ContractCase')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='dispute_resolution.ContractStage')),
                ('user_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_emitted', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ManyToManyField(related_name='events_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_account', models.CharField(db_index=True, max_length=65, unique=True, verbose_name='ETH Address')),
                ('organization_name', models.CharField(default='Some org', max_length=45, verbose_name='Organization')),
                ('tax_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='TAX Identity')),
                ('payment_num', models.CharField(default='not valid payment number', max_length=40, verbose_name='Payment card')),
                ('files', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
