# Generated by Django 2.0.7 on 2018-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcase',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
