# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0002_auto_20180711_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('dispute_start_allowed', models.DateField(blank=True, null=True)),
                ('dispute_started', models.DateField(blank=True, default=None, null=True)),
                ('result_file', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='content_type',
        ),
        migrations.AddField(
            model_name='contractcase',
            name='files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractcase',
            name='finished',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractcase',
            name='party',
            field=models.ManyToManyField(related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='event_type',
            field=models.CharField(choices=[('fin', 'Finished'), ('dis_open', 'Disput Opened'), ('open', 'Opened'), ('disp_close', 'Dispute Closed')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='user_by',
            field=models.ManyToManyField(related_name='events_emitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='user_to',
            field=models.ManyToManyField(related_name='events_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='eth_account',
            field=models.CharField(db_index=True, default=0, max_length=65, unique=True, verbose_name='ETH Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='organization_name',
            field=models.CharField(default='Some org', max_length=45, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='payment_num',
            field=models.CharField(default='not valid payment number', max_length=40, verbose_name='Payment card'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tax_num',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TAX Identity'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
        migrations.AddField(
            model_name='contractstage',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dispute_resolution.ContractCase'),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='dispute_starter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='stage',
            field=models.ManyToManyField(related_name='events', to='dispute_resolution.ContractStage'),
        ),
    ]
