# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0003_auto_20180712_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstage',
            name='result_file',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
