# Generated by Django 2.0.7 on 2018-07-12 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0004_auto_20180712_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyevent',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
