# Generated by Django 2.0.7 on 2018-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0004_auto_20180723_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractstage',
            name='dispute_finished',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
