# Generated by Django 2.0.7 on 2018-08-02 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0005_contractstage_dispute_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstage',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dispute_resolution.ContractCase'),
        ),
        migrations.AlterField(
            model_name='notifyevent',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dispute_resolution.ContractCase'),
        ),
        migrations.AlterField(
            model_name='notifyevent',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dispute_resolution.ContractStage'),
        ),
        migrations.AlterField(
            model_name='notifyevent',
            name='user_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_emitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notifyevent',
            name='user_to',
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='user_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
