# Generated by Django 2.0.7 on 2018-07-16 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0005_notifyevent_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstage',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='dispute_resolution.ContractCase'),
        ),
        migrations.AlterField(
            model_name='contractstage',
            name='dispute_starter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractstage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifyevent',
            name='event_type',
            field=models.CharField(choices=[('fin', 'Finished'), ('disp_open', 'Disput Opened'), ('open', 'Opened'), ('disp_close', 'Dispute Closed')], default='open', max_length=10),
        ),
        migrations.RemoveField(
            model_name='notifyevent',
            name='stage',
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='dispute_resolution.ContractStage'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='notifyevent',
            name='user_by',
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='user_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='events_emitted', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='notifyevent',
            name='user_to',
        ),
        migrations.AddField(
            model_name='notifyevent',
            name='user_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='events_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
