# Generated by Django 2.0.7 on 2018-08-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0006_auto_20180802_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifyevent',
            options={'ordering': ('-id',)},
        ),
    ]
