# Generated by Django 2.0.7 on 2018-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute_resolution', '0007_auto_20180802_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyevent',
            name='event_type',
            field=models.CharField(choices=[('open', 'Case Opened'), ('fin', 'Case Finished'), ('disp_open', 'Dispute Opened'), ('disp_close', 'Dispute Closed')], default='open', max_length=10),
        ),
    ]
